### ISSUE TITLE
Display events not from the source

### ISSUE THREAD

**Issue by halfblood99** [VolkovLabs/volkovlabs-calendar-panel#107]
I've add to grafana alert rule and then it start displaying on my calendar, although the source of the calendar JSON API
Alert rule from Infinity. How can I hide these events?

![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/67783680/493f0c24-f449-4e4e-bd59-038fe6684ec4)
![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/67783680/5a80a58d-30b5-4fe5-ab0c-8f2d3aa9045a)

**Comment by mikhail-vl** [comment]
@halfblood99 You can disable and enable showing annotations in the calendar.

  In the upcoming version, you can select to show alerts and/or manual annotations.
