### ISSUE TITLE
Click event on date?

### ISSUE THREAD

**Issue by yosiasz** [VolkovLabs/volkovlabs-calendar-panel#108]
Does this amazing plugin have date click event?

So when I click on a certain date I can capture that date value

Again yet another amazing plugin from your team!!

**Comment by mikhail-vl** [comment]
@yosiasz How do you want to capture it?

  It's something we can add.

**Comment by yosiasz** [comment]
I am not sure but maybe a json with multiple date data types?

`{
 epoch: 1688385199608,
 utcdatetime: 2023-07-03 11:54:58
}`

Is that what you were asking?

**Comment by mikhail-vl** [comment]
@yosiasz I mean, do you want to copy this value to the clipboard, send it using Event Bus, update the dashboard variable, or something else?

**Comment by yosiasz** [comment]
Update a dashboard variable for now sounds great! Though it sounds like an unusual pattern. in plugin development can you can a custom global variable? probably not

**Comment by mikhail-vl** [comment]
@yosiasz All global variables are reserved.

  The legacy calendar supports clicking on two dates, and then you can update the selected time range.
  You can add events with on-click functionality using data links, which can modify dashboard variables.

  Alternatively, you can implement your own calendar using Dynamic Text with custom logic.
