### ISSUE TITLE
Make annotations but not alerts appear in the calendar panel

### ISSUE THREAD

**Issue by gomgomshrimp** [VolkovLabs/volkovlabs-calendar-panel#109]
We are receiving Kubernetes deployment completion status through grafana annotations api.
Are there any plans to add something to make annotations appear in the calendar panel but not alerts?

![스크린샷 2023-07-26 08 55 04](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/12162614/ffb95bce-bcf5-474e-8430-325d2ea512f7)

As you can see in the attached screenshot, the time series panel can only show annotations, but the calendar will always show annotations and alerts together.

This is quite inconvenient for users who use alerts a lot, and I think it would be better if only annotations could be displayed.

If there's a way to do this that I'm not aware of, please let me know.

**Comment by gomgomshrimp** [comment]
![schema-around-config](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/12162614/1100a44d-a990-4e94-b5c1-26d1563c687a)
I found the `Grafana HTTP API Data Source` in one of your labs.
From the picture, it looks like I can filter the annotations.
Could this be a solution?

**Comment by mikhail-vl** [comment]
@gomgomshrimp, The calendar panel uses Annotation API calls to retrieve annotations within the time range. There is no options to filter annotation in the panel.

  I have not tried the HTTP API Data Source with the Calendar panel, but I believe it should work.
  Let me know if it works for your use case. There are YouTube tutorials if you need any help to configure it.

**Comment by Glafkon** [comment]
Alert annotations don't go away when "Annotations" on widget settings is "Disabled".
![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/135970047/2a56a07f-8fdf-41c2-a38c-eaac0f2771a2)
Even when the alert rule is deleted, these annotations remain on the calendar. Use in this format is not possible :(
Grafana v.10.0.3
Plugin Calendar v.2.0.0

**Comment by mikhail-vl** [comment]
@Glafkon Thank you for reporting the issue. Please keep issues separate for tracking.

  I found the issue and missing tests. We will add tests and release a new 2.0.1 fix tomorrow.

**Comment by mikhail-vl** [comment]
@Glafkon We released a new version and submitted to the Grafana team for review.

![Screenshot 2023-08-03 at 12 44 45](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/47795110/72a783b1-4de5-49fc-b422-3f1f4cfa583d)

**Comment by Glafkon** [comment]
> @Glafkon We released a new version and submitted to the Grafana team for review.
> 
> ![Screenshot 2023-08-03 at 12 44 45](https://user-images.githubusercontent.com/47795110/258180007-72a783b1-4de5-49fc-b422-3f1f4cfa583d.png)

Hello. I confirm, the problem with the display of events (alert rules) after installing 2.0.1 was resolved. I will be watching for further work. Thanks!

**Comment by mikhail-vl** [comment]
@Glafkon Thank you for confirming.

**Comment by gomgomshrimp** [comment]
@mikhail-vl 
Sorry for the delayed response due to vacation.
If I upgrade to the 2.0.1 version of the calendar plugin, will this also be a workaround for the first issue I asked about?

**Comment by mikhail-vl** [comment]
@gomgomshrimp Selection for Alerts and Annotations with Max Limit will be added in #121.
