### ISSUE TITLE
Wrong Start Time and End time

### ISSUE THREAD

**Issue by cheesewizz** [VolkovLabs/volkovlabs-calendar-panel#120]
Hi,

We have webbased calendar connected to MySQL Database, i made a query to show in the Grafana Calendar it was successfully although i noticed that the start time and end time were wrong, I also changed the "Change time settings" but there was no change.
![wrong](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/14123082/dc6da38a-1fed-467a-bba2-5cef0af9c189)

the start time and end time should be 11:00AM to 12:00PM

here is my query 
SELECT title,start,end, location, creation_date FROM `calendar_events` ORDER BY creation_date

thanks in advanced

**Comment by mikhail-vl** [comment]
@cheesewizz Do you return timezone from the database? What do you see in the Table view?

  If you return timezone, then it most probably shifted to the browser's time zone.

**Comment by mikhail-vl** [comment]
@cheesewizz I hope you were able to resolve your timezone issue.

  Let us know if there is anything else.

**Comment by cheesewizz** [comment]
> @cheesewizz Do you return timezone from the database? What do you see in the Table view?
> 
> If you return timezone, then it most probably shifted to the browser's time zone.

Hi mikhail-vl

Sorry for not replying immediately

yes i shifted to browser timezone but nothing happened still same time.

**Comment by mikhail-vl** [comment]
@cheesewizz How is your data looks like?

  Can you emulate the error using Static Data Source and send me dashboard JSON to take a look.

**Comment by cheesewizz** [comment]
![dashboard](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/14123082/986aeb1c-dc4e-4929-9dc2-d641656e0c7d)

![dash2](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/14123082/2e412239-2759-4b26-981d-847311f9f8dd)

json file see calendar json format.txt
[calendar json format.txt](https://github.com/VolkovLabs/volkovlabs-calendar-panel/files/12403983/calendar.json.format.txt)


Thanks

**Comment by mikhail-vl** [comment]
@cheesewizz Thank you. We will take a look and get back to you.

**Comment by Carmelito80** [comment]
Same problem here. 
In the tabular view the time is correct, while in the calendar view we have the date ahead of two hours, as you can see from the screenshots below. What can we do?

![Screenshot 2023-08-29 161048](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/29299873/9822037a-6a67-43b5-b05f-6e09d049d951)
![Screenshot 2023-08-29 161032](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/29299873/9fe65fbe-3b31-4e54-b00b-522a9359f18b)

Thank you

**Comment by cheesewizz** [comment]
Noted, thank you very much

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 4, 2023 at 10:13 PM, Mikhail ***@***.***> wrote:   


@cheesewizz @Carmelito80 We are working on a fix.

It will be a part of the upcoming release.

**Comment by mikhail-vl** [comment]
@Carmelito80 I will plan to release it later this or next week.
