### ISSUE TITLE
Week view with location under big calendar

### ISSUE THREAD

**Issue by cheesewizz** [VolkovLabs/volkovlabs-calendar-panel#125]
Hi

can be show to week view the Event name, start time - end time and location under Big Calendar.

see image sample. 3333e338888.jpg
![3333e338888](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/14123082/7870e906-8c98-4da6-acc5-78e46750efe5)

thanks

**Comment by mikhail-vl** [comment]
@cheesewizz Thank you for opening the issue.

  I like an idea to have a location as a separate field to display under or next to the title depends on the available space.
  We will plan it for the upcoming release.
