### ISSUE TITLE
Hide one or more blank time slots with no events

### ISSUE THREAD

**Issue by sqkkyzx** [VolkovLabs/volkovlabs-calendar-panel#138]
## My Dilemma:
In the week and day views of the Grafana calendar panel, it defaults to displaying the entire time range from 00:00-23:59, even if there are no events between 00:00 - 08:00 and 22:00-23:59. This results in the time slot from 00:00 - 08:00 occupying a large amount of screen space. For mobile display, this means that 4/5 of my entire screen is not displaying any useful information, and even on a computer screen, these blanks also occupy half of the entire panel.

## Suggestion:
There needs to be a configuration option that allows me to choose to hide one or more blank time slots where it is clear that no events will occur.

**Comment by sqkkyzx** [comment]
You can see the view on my phone, there's a tremendous amount of blank space. In fact, on the PC, the large amount of blank space from 00:00 - 08:00 is equally frustrating.

![df8a7d38e1dc46b30096969c6374fa2](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/77138105/f95e6128-ddb3-472b-98a9-9856ec169a94)

**Comment by mikhail-vl** [comment]
@sqkkyzx I was thinking of implementing an `Agenda` view, which may work for you. It just displays a list of activities with no extra space.

![Screenshot 2023-10-24 at 12 42 15](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/47795110/b309543d-2bcc-4fe8-b6a8-3af4488da610)

I am not sure if `BigCalendar` library supports hiding empty time slots. We will check.

**Comment by sqkkyzx** [comment]
@mikhail-vl 

Thank you for your reply. Your new view may be useful for some people. However, for me, I need to use the `week` view so that I can see the free time of a certain teacher this week in order to schedule lessons for them. The `week` view is my best choice, even if it is not very convenient now, but it can works for my core needs.

I briefly looked at the page's DOM. If I want to hide the blank space from 00:00 to 08:00, I need to delete 8 `<div class="rbc-timeslot-group">` from each `<div class="rbc-time-gutter rbc-time-column">`, and recalculate the `top` and `height` percentages in the css of each event in `<div class="rbc-events-container">`.

If you can't do this in the plugin, I will have to embed the panel in a page using an iframe, and then manipulate these doms and css with additional js. This is terrifying.

**Comment by mikhail-vl** [comment]
@sqkkyzx Thank you for explaining.

  We will check what can be done.
