### ISSUE TITLE
Displaying out of order on day view

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-calendar-panel#144]
Prehaps this use case doesnt really fit here, but it seems like it could work. We are using this panel to display logon events. However some events happen within a minute of each other for example
![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/662108/ea994456-8f1c-43d3-a5dd-8f8dfe5903e0)

In this image you can see that the Unlocked event at 12:10 is happening before the lock event at 12:10

the data source has it listed down in seconds and shows the lock event happens before at 12:10:22

![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/662108/718019ba-f34f-454e-9971-97382bdb7298)

I have tried ordering the SQL query but it doesnt make a difference. Is there anything i can do here?

**Comment by mikhail-vl** [comment]
@craftzneko I believe, the BigCalendar library doing it's own visual ordering based on hours and minutes.

  @asimonok, any ideas?

**Comment by craftzneko** [comment]
Any ideas or work around suggestions to could do here @asimonok / @mikhail-vl  i did see one other user using big calender who mentioned they were sorting the date field as a string that was causing out of order events, is that part of the issue here. Can i make changes to my data to make this work do you think? Cheers :-)

**Comment by asimonok** [comment]
The problem is in using no-overlap algorithm. I created an PR - https://github.com/jquense/react-big-calendar/pull/2469 in BigCalendar to keep original events order. If they don't accept it, we will move no-overlap algorithm to our code to solve the issue.

**Comment by craftzneko** [comment]
HI @asimonok did this go anywhere, merge still seems open, it seems a lot of these dont end up getting merged. Is there anything that can be done on this repo to resolve? Cheers

**Comment by mikhail-vl** [comment]
@craftzneko The developer of the Big Calendar has very little activity on GitHub recently.

  We will need to check what is the current state of the project and figure out the plan to move forward with the plugin.

**Comment by craftzneko** [comment]
That would be great @mikhail-vl, don't suppose you have any good ideas that might work in the meantime as a workaround?
