### ISSUE TITLE
Hide end time when none is supplied

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-calendar-panel#145]
I am using the calendar to display logon events but they dont have end times on. The display by default shows an end time, which i understand is to give each item a height agasint the time, however is it possible to hide the end time as it looks odd in my use case to have a logon event with an end time

![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/662108/66b3ef2c-9481-4b67-860b-91ee4f263569)

**Comment by mikhail-vl** [comment]
@craftzneko Thank you for submitting the feature request.

  You are correct, that the end time is used to determine the height. We will take a look what can be done.

**Comment by craftzneko** [comment]
Thanks @mikhail-vl

**Comment by craftzneko** [comment]
Hi @mikhail-vl , i found this really old stack question, is this related and potentially helpful?

https://stackoverflow.com/questions/46684396/react-big-calendar-hide-start-time-end-time-from-time-slot

**Comment by craftzneko** [comment]
HI @mikhail-vl just wondering if you managed to find any solution to this? All the best

**Comment by craftzneko** [comment]
HI sorry to ask again i am desperate to get this functional. It works except all the users are really confused with the end time as it implies in my use case that a logon event had an end time. I need to hide this, if this cant be done here code is there any suggestion how i might achieve this on my side? @mikhail-vl / @asimonok

**Comment by mikhail-vl** [comment]
@craftzneko We discussed it with @asimonok and looking into it.

**Comment by craftzneko** [comment]
@mikhail-vl  @asimonok  Thank you both ❤
