### ISSUE TITLE
Built-in time range variables not updated when selecting the day view in the calendar

### ISSUE THREAD

**Issue by bertrandpasset** [VolkovLabs/volkovlabs-calendar-panel#146]
Hi, 
We use the calendar v2.3.1 with Grafana OSS v10.1.2. Built-in time range variables are not updated when selecting day view in calendar. After that the day by day navigation in the calendar has no effect on the dashboard timepickers.

![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/121937824/a50146a0-031b-45ea-8ca6-73a4fc009df0)

But if we select a day in the dashboard timepickers then the calendar works correctly.

We need help. :-)

**Comment by mikhail-vl** [comment]
@bertrandpasset That's expected behavior. Calendar panel does not request data again if Day view is in the same time range as Weekly/Monthly. Time Range will be updated when out of range.

  Do you see any issues with the current logic?

**Comment by asimonok** [comment]
Close due to no additional details

@bertrandpasset please let us know if the issue is still relevant for you
