### ISSUE TITLE
Multi-Day Events in Hour-View

### ISSUE THREAD

**Issue by peterloeser** [VolkovLabs/volkovlabs-calendar-panel#148]
Is it possible to display multi-day events in the day and week view in the hour view?
I would like to better recognize overlapping events.

**Comment by asimonok** [comment]
Hi @peterloeser. 
Thanks for the feature request. All day events are shown in the top,  it's a limitation of the current library which we can't change and also it's the same as how google calendar works which we try to follow. 

As a workaround, you can split your events to make them shown in hour view
