### ISSUE TITLE
Change the display text for location

### ISSUE THREAD

**Issue by lembi2001** [VolkovLabs/volkovlabs-calendar-panel#163]
Morning, I am wondering if there is a way to change the "Location:" text in the event flyout? I also need to discover a way to unlink the calendar from the Date Time picker as I would like it to operate independent of other items on the dashboard. At present having the current day selected in the calendar results in other items not working. My dashboard is based off a selected "year" custom variable.

**Comment by lembi2001** [comment]
I have tried to modify the "Location:" string in the localization file en.json but this breaks the calendar plugin completely. I'm assuming that this is related to how the Locale files are processed and applied based on the strings within them. Apologies if I am way off the mark, never written/modified a grafana plugin before.

**Comment by mikhail-vl** [comment]
@lembi2001 Thank you for submitting feature request.

  All community Grafana plugins are signed and all files have a checksum, which verified when plugin is loaded. You can modify the localization file, but you need remove MANIFEST file and allow to load plugin as unsigned.

  We can customization option to update the location title.

  Please open a new issue for unlinking Date/Time Picker, which is a good idea. We accept only one feature request per opened issue for tracking purposes.

**Comment by lembi2001** [comment]
Thank you for your response. I have raised the request for the removal of the dependency on Date/Time Picker

**Comment by mikhail-vl** [comment]
Resolved in #178
