### ISSUE TITLE
Remove the dependency on Date/Time Picker

### ISSUE THREAD

**Issue by lembi2001** [VolkovLabs/volkovlabs-calendar-panel#164]
Request to remove the dependency on the Date/Time Picker. For my use case I use a custom variable to control what is displayed and adding the calendar into this dashboard results in either the calendar displaying no data or the dashboard items breaking if the date is changed on the calendar.

**Comment by mikhail-vl** [comment]
@lembi2001 Thank you for feature request. We will add it in the upcoming release.
