### ISSUE TITLE
Customise what fields are displayed in the event bubble

### ISSUE THREAD

**Issue by carlocea9** [VolkovLabs/volkovlabs-calendar-panel#171]
Hi,

I believe this request is somewhat related to https://github.com/VolkovLabs/volkovlabs-calendar-panel/issues/29 and https://github.com/VolkovLabs/volkovlabs-calendar-panel/issues/163 but I am not sure if it directly ties.

At the moment, the event bubble only displays from the following 2x fields:
 - Text
 - Location

My usecase, it is easier to see if the "Description" field is shown in the event bubble.
The easy workaround is to swap the mapping of the "Description" and "Location" field - which works fine.
But when you click the event bubble, the "Event Details" also swaps the fields which looks weird.
I find it more appropriate for the "Description" field to be on the bigger text as sometimes "Description" can get truncated in the event bubble.

See attached photo for reference.
![Capture](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/59286713/faca1501-1006-4fd4-b1b4-cc257d520176)

**Comment by mikhail-vl** [comment]
@carlocea9 Thank you for feature request.

@vitPinchuk Please add a panel option to select fields to display.
