### ISSUE TITLE
Annotations text is not displayed on Day, Week, and Work Week views

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-calendar-panel#185]
Custom annotations are displayed for Month, Agenda views in the latest 3.1.0.

**Comment by vitPinchuk** [comment]
@mikhail-vl 
I use "Weekly" dashboard with Time Series panel, to create annotations. And I see in event only time without text. Correct. But I created event and range of event a few hours, and I see time + text for event (gray in screenshot)  
  

![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/146737590/121d38f5-1f9c-450d-a6cd-25186b1383ab)  
 
If the annotation has a short time range, the text is not placed in an event on the calendar. The annotation contains text it just doesn't fit in the event.

Our `BigEventContent` component display time first then text; 
```javascript  
 <>
      {showTime && !event.resource.allDay && (
        <div className={styles.date}>
          {localizer.format(event.start as Date, 'LT')}
          {!event.resource.noEndTime && ` – ${localizer.format(event.end as Date, 'LT')}`}
        </div>
      )}
      {event.title}
      {!!event.resource?.location && <span className={styles.location}>{`: ${event.resource.location}`}</span>}
    </>
```

I set `showTime = {false}` and after that I see text, but we need display time   

![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/146737590/5a9e63de-a55d-49f1-9dac-8af685fab4e7)
