### ISSUE TITLE
Update variables with static datasource for time range source dashboard

### ISSUE THREAD

**Issue by asimonok** [VolkovLabs/volkovlabs-calendar-panel#187]
When static datasource v4.0.0 is ready, update `to` variable on:
Take from variable value and add 3 options (+1, 2, and 3 weeks). It's more common use case when date variables depend on other variables

**Comment by mikhail-vl** [comment]
Business Input Data Source 4.0.0 released: https://github.com/VolkovLabs/volkovlabs-static-datasource/releases/tag/v4.0.0
