### ISSUE TITLE
Daterange filter

### ISSUE THREAD

**Issue by afk-proficoder** [VolkovLabs/volkovlabs-calendar-panel#193]
First of all I really like to thank you for your work on this cool plugin on Grafana :) 
We have a use case where we want to see the "Agenda" view on a specific Date Range (for ex. 05.27.2024 - 05.29.2024).

Would it be possible to add such a Date Range filter or that the "Agenda" changes it's view according to the current Dashboard "From" and "To" values?
![2024-05-28 11_50_44-](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/54726438/48ce3c4e-cb87-4cd8-baa3-68fb9df763c0)
![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/54726438/5e260093-0ebf-482c-b14d-c2ace18f1715)

**Comment by mikhail-vl** [comment]
@afk-proficoder Calendar panel displays events from the selected data source.

  Data Source in the query editor should select data based on the provided Time Range.
  We will introduce new feature to select To and From independently from Time Range in the future version: https://github.com/VolkovLabs/volkovlabs-calendar-panel/pull/179. But in your case you should use filters in the data source.

  Please let me know if it helps.

**Comment by afk-proficoder** [comment]
Hi @mikhail-vl, thanks for your quick response.

I overlooked issue #179, I think this will help to fix our use case.

In the meantime, I will attempt to accomplish this using filters in the data source and will update this issue if it works.

**Comment by mikhail-vl** [comment]
@afk-proficoder #179 is merged and will be a part of the upcoming release.

  Meanwhile, we identified the issue with Agenda view. It will be improved in the upcoming release.

**Comment by mikhail-vl** [comment]
Resolved in #196 and will be a part of the upcoming release.
