### ISSUE TITLE
Translate Weekdays and Months

### ISSUE THREAD

**Issue by GustavoBazinga** [VolkovLabs/volkovlabs-calendar-panel#198]
Hey, guys.
How can I translate the days of the week and monthes into Portuguese? I'm setting up a an agenda environment for people who do not have knowledge of English, but i have not benn able to translate these fields (others too).
I edited the files module.js and module.js.map in the references found for the months, but this only made the plugin corrupt and need to reinstall.

**Comment by mikhail-vl** [comment]
@GustavoBazinga Thank you for opening feature request.

  We will look into adding Portuguese language in the upcoming release.

  Our plugins are signed with included checksums for all files to avoid unauthorized modification and corruption. We don't recommend to update plugins manually.
