### ISSUE TITLE
Option to make week start at Monday instead of sunday

### ISSUE THREAD

**Issue by Tricked-dev** [VolkovLabs/volkovlabs-calendar-panel#214]
Hello where I live calenders usually start the week on Monday could a option for this be added? For both week and month?

**Comment by vitPinchuk** [comment]
@Tricked-dev Thank you for your question.

_For the Work and Work Week layouts, the plugin considers the Grafana system settings when choosing the first day of the week - Saturday, Sunday, or Monday, or uses the default day from Grafana settings._ 
 
Here is part of the documentation: 
[Work and Week](https://volkovlabs.io/plugins/volkovlabs-calendar-panel/basic-config/#week-start)  
[Layout](https://volkovlabs.io/plugins/volkovlabs-calendar-panel/layout/#week-and-work-week)  

This is also works fine for month

Here is my default profile settings 
![image](https://github.com/user-attachments/assets/f5f73147-c47a-4523-b10a-f73f35c0fefa)
 
And week starts from Sunday
![image](https://github.com/user-attachments/assets/40dfa424-2fb6-45fb-9676-132647cef168)

Please, change profile settings `Week start` -> `Monday`
![image](https://github.com/user-attachments/assets/d5375c7e-069e-40e5-b1a8-273f35e583ab)

And week starts from Monday

![image](https://github.com/user-attachments/assets/4b11686c-2c2b-4581-bd76-0bce2c3dc912)

**Comment by Tricked-dev** [comment]
Thanks for the quick response, that works 🎉
