### ISSUE TITLE
Calendar is displayed for next month when "this month" is selected in TimePicker. This happens only on first render.

### ISSUE THREAD

**Issue by Kshitijde** [VolkovLabs/volkovlabs-calendar-panel#220]
This is observed when the system time zone and the time zone in the time picker are different. (The system time zone selected is IST, and the time zone in the time picker is UTC ). 

<img width="779" alt="image" src="https://github.com/user-attachments/assets/0c9c97f2-89d7-4ff0-a733-7160033a0023">

Strangely, it auto-corrects itself when we edit the panel or click on any configuration option (basically on the next re-render).

Moreover, when we click on day and back to month. I can see the following time in the time picker:

<img width="773" alt="image" src="https://github.com/user-attachments/assets/1381aca8-55e8-4bdf-af15-d55a547226fe">

We are using the calendar plugin with Grafana 10. 

Expected behavior: The calendar should show the current month's calendar when the "this month" option is selected. Likewise it should pick time from 12 am to 12pm accurately (refer image 2)

**Comment by mikhail-vl** [comment]
@Kshitijde Thank you for reporting the issue.

  We reproduced it and will fix in the upcoming release.
