### ISSUE TITLE
Lots of crashing and Unsuported Color message

### ISSUE THREAD

**Issue by craftzneko** [VolkovLabs/volkovlabs-calendar-panel#222]
not sure if i happen to have a corrupt dashboard but after the last but one update the calendar fails to show with this error

![image](https://github.com/user-attachments/assets/de6c1d00-924c-4c62-b438-1c77b9e22712)

When i try and remove the override here
![image](https://github.com/user-attachments/assets/26d2824b-be88-41ac-98d1-4e14c660f385)

or change these options

![image](https://github.com/user-attachments/assets/8f8f1e04-ee08-407c-bae0-f27e6de06579)

I get

![image](https://github.com/user-attachments/assets/8cfd1838-3589-4e9b-8c5d-809f4de832d8)

Additionally this is the only panel on the dashbaord but i get this warning (which may be a grafana issue anyway)

![image](https://github.com/user-attachments/assets/f0ee9a50-6878-4e26-9088-9d31fe131e1e)

The color issue seems to go away if i change from using single color to something like shades of a color

**Comment by mikhail-vl** [comment]
@craftzneko What is the version of Grafana and plugin do you use?

  Please provide JSON file of the test dashboard with errors to troubleshoot.

**Comment by craftzneko** [comment]
just realised i am a few revisions out on grafana using 10.4.2, will update and check still an issue

**Comment by mikhail-vl** [comment]
@craftzneko Please keep us updated.

**Comment by craftzneko** [comment]
That does seem to have solved the issue 👍  Thanks

**Comment by mikhail-vl** [comment]
@craftzneko Thank you for confirming!
