### ISSUE TITLE
Day/Schedule view

### ISSUE THREAD

**Issue by marcusolsson** [VolkovLabs/volkovlabs-calendar-panel#42]
This proposes to add a Schedule view which lays out calendar events as a vertical feed to make it easier to see upcoming events during the day.

Here's an example from Google Calendar:

![Screenshot 2022-03-09 at 21 51 00@2x](https://user-images.githubusercontent.com/8396880/157533799-e6f21646-cbec-45b3-9c4f-003d0822aebd.png)

### Discussed in https://github.com/marcusolsson/grafana-calendar-panel/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **fmuell2** May 17, 2021</sup>
When using the Grafana Timerange Today the calender shows the whole week. In our usecase its hard to read the entry titels. It would be better if there was a possiblity to show only one day when the timerange Today is selected</div>

**Comment by mikhail-vl** [comment]
Day Schedule view will be implemented in #55.
