### ISSUE TITLE
More... button not visible 

### ISSUE THREAD

**Issue by ajinkya-mulay** [VolkovLabs/volkovlabs-calendar-panel#49]
We are using calendar plugin with grafana 8.4.5 OSS version. We have created a dashboard using calendar plugin. We have observed sometime "N more..." button is not visible event if there are more than 2 data points on the same day. 

![image](https://user-images.githubusercontent.com/95682162/168570143-6b46180b-1e99-4bd0-8755-3360bb36384a.png)

In the above example where mouse cursor is there are some data point but more... button is not visible.

We had to increase the height of the panel to make it visible. 

![image](https://user-images.githubusercontent.com/95682162/168570648-ca00e7b2-5508-4330-8de6-ce1af0d6fda3.png)

Can you please address this issue ?

**Comment by mikhail-vl** [comment]
@ajinkya-mulay I see the same issue on the latest Grafana 9.3.1.

  We will work on this issue after refactoring.

![Screen Shot 2022-12-13 at 08 38 55](https://user-images.githubusercontent.com/47795110/207339036-2e113315-9c00-4ec0-a78a-99a578117f75.png)
