### ISSUE TITLE
Event length on Day view updates

### ISSUE THREAD

**Issue by willk1** [VolkovLabs/volkovlabs-calendar-panel#55]
Hi Volkov team, 

Love the current calendar plugin but was curious to see if there were a way to adjust the events to where each events size on the calendar varied based on its duration. So for an example adding time from morning to evening on the left most side and a having a two hour event be a larger block on a day then say a one hour or 30 minute event.

**Comment by mikhail-vl** [comment]
@willk1 Thank you for your support.

  We are planning improvements to support multiple events on the same day and I love the idea.
  We will plan it for one of the upcoming releases.

**Comment by willk1** [comment]
excellent thank you! Ideally something like this would be great. 
![Screen Shot 2022-11-02 at 9 46 46 AM](https://user-images.githubusercontent.com/54449804/199550732-6f5a2d26-deea-495b-8c98-6e618e4c0c36.png)

**Comment by mikhail-vl** [comment]
@willk1 I was thinking to allow to switch from Monthly to Weekly. I will look into it.

**Comment by willk1** [comment]
Hey just wanted to see what the updated timeline was for this change?

**Comment by mikhail-vl** [comment]
@willk1 We started working on the Calendar plugin and plan to release a new version this week.

**Comment by mikhail-vl** [comment]
@willk1 Calendar plugin has a lot of legacy code, which requires refactoring and adding test coverage before we can start adding features.
  We expected to finish refactoring in this release and add some features, but refactoring is halfway done and will require 2-3 working days to finish it.

  We will continue working on the plugin between the projects. The next milestone is Dec, 31.

**Comment by willk1** [comment]
Thank you for taking the time and considering my change. Really appreciate all your teams work.

**Comment by mikhail-vl** [comment]
@willk1 We almost finished refactoring and will release a new version today. We fixed many issues and introduced new styles similar to the current Google Calendar view.

![screenshot](https://user-images.githubusercontent.com/47795110/221008643-6b163035-6802-4b41-ab63-974b90aa1002.png)

To get to the view you are looking for we need to align events by hours and will do it first thing in the upcoming release.

![Screen Shot 2023-02-23 at 14 21 09](https://user-images.githubusercontent.com/47795110/221008904-dea7d2a0-72a4-444b-be21-d81d1f254887.png)

Thank you for your support.

**Comment by mikhail-vl** [comment]
Day view is implemented using the Big Calendar library in v2.0.0.
  Resolved in https://github.com/VolkovLabs/volkovlabs-calendar-panel/pull/106.
