### ISSUE TITLE
Choose color for different calender queries

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-calendar-panel#64]
### Discussed in https://github.com/VolkovLabs/volkovlabs-calendar-panel/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **fmuell2** May 31, 2021</sup>
If you add multiple queries for calender entries in the new 0.4.2 panel version the entries are shown in different colors. Is there any way to set the used color for each query? 

E.G. i would like to change the color of emergency change entries to red.</div>

**Comment by mpowelltech** [comment]
Is this a feature that could be prioritized via some sort of sponsorship? 
We've been looking for this for months now - just the simple ability to set the color of a calendar entry based on some sort of field input.
I know it was scheduled for release a few months back, but haven't had any update since.

**Comment by mikhail-vl** [comment]
@mpowelltech Last two months, we have been working on improving documentation for all our maintained plugins to support future developments: https://volkovlabs.io/plugins/. We are overwhelmed with the inflow of questions and have ~50 outstanding issues to deal with.

  We are finishing documentation as we speak and will start working on plugins one by one releasing new versions. The calendar is one of our top priorities to improve this week.

  You are welcome to sponsor using GitHub sponsorship.

**Comment by mikhail-vl** [comment]
@mpowelltech Colors will be a part of the upcoming release 1.2.0 later today.

Here are examples:

![screenshot](https://user-images.githubusercontent.com/47795110/221027266-eaabac71-68c5-4109-a439-06539120bc19.png)

![Screen Shot 2023-02-23 at 15 07 42](https://user-images.githubusercontent.com/47795110/221027123-996dcbce-09ba-455b-842c-ebfeaaf16dc4.png)

Let me know if there is anything else.
