### ISSUE TITLE
[Feature Request] Integrate time series data

### ISSUE THREAD

**Issue by DataScienceIsCool** [VolkovLabs/volkovlabs-calendar-panel#71]
Hi,

maybe I'm missing something and this is already possible but here is my case:
I would like to display a single value per day from a Flux query in the calendar. 
Your calendar panel would be very useful, because it would allow intuitive
time range selection based on the contents of the calendar. 
Is there a way to solve my use-case?

**Comment by mikhail-vl** [comment]
@DataScienceIsCool Have you tried to use the panel? Check out documentation and video tutorial to get Started: https://volkovlabs.io/plugins/volkovlabs-calendar-panel/

  We will release a new version 1.2.0 later today with improvements and bug fixes.
