### ISSUE TITLE
Gaps between multi-day events

### ISSUE THREAD

**Issue by mpowelltech** [VolkovLabs/volkovlabs-calendar-panel#85]
Hi Team,

Really appreciate the work on adding color functionality.

Have another curious issue, where there are massive gaps in days with multi-day events.
Pictured here with the red arrow I can confirm there are no events missing, there's just a big gap, that's taking up a whole bunch of space on the days, which means the calendar has to be massive to fit more than the top 2 or 3 events in.

![image](https://user-images.githubusercontent.com/36752644/221447671-31312d41-22e4-427b-91b9-46afea516b92.png)

Thanks again!

Grafana version: 9.3.6
Plugin version: 1.2.0

**Comment by mikhail-vl** [comment]
@mpowelltech I found this issue when did refactoring. This is the way how original plugin keeps consistency for MultiDay events. You see gaps for events which happens weeks prior. 

  Looking at the Google Calendar it just keeps MultiDay events gaps for the current week and then remove them.
  Thank you for opening to issue, I will see how to align It properly without gaps for the weeks after the event finished in the upcoming version.

  How do you like the new look and feel? Anything other issues or suggestions?

**Comment by mpowelltech** [comment]
@mikhail-vl That'd be great!

The colours are great to have - I couldn't figure out how to dynamically set each event to a unique colour (I would have expected that picking any number field and selecting the Classic Palette option could have done this, but when I do that everything is green. The (By Value) options all work great and I have worked around generating random colours by just using thresholds with random colours:
![image](https://user-images.githubusercontent.com/36752644/221466943-cdb35991-b71f-4afc-a695-f845e1224473.png)

My only other feature request other than fixing these gaps is one I have just created in https://github.com/VolkovLabs/volkovlabs-calendar-panel/issues/86 to do with spanning event titles across multiple days for readability.

If those two things are implemented, this would be perfect for us, so looking forward to it!

**Comment by mikhail-vl** [comment]
Classic Palette colors works for different queries (data frames). It's actually a good feature to add. You are welcome to open a separate issue instead of doing a workaround.

**Comment by mikhail-vl** [comment]
@mpowelltech We updated logic to eliminate multi-day gaps. I would appreciate it if you could test it and confirm the update. You can download the latest signed build from CI: https://github.com/VolkovLabs/volkovlabs-calendar-panel/actions/runs/4336783927

  Please let me know.

**Comment by mikhail-vl** [comment]
@mpowelltech We added an option to choose colors based on Frame or Event Id.

  CI build: https://github.com/VolkovLabs/volkovlabs-calendar-panel/actions/runs/4336920439
