### ISSUE TITLE
Request: Event names should be able to span across multiple days

### ISSUE THREAD

**Issue by mpowelltech** [VolkovLabs/volkovlabs-calendar-panel#86]
Thanks again to the team on maintaining this plugin.

One other feature request that would be great, is being able to have event names span across multiple days.

![image](https://user-images.githubusercontent.com/36752644/221467440-c6d9172e-69a5-4127-935e-ae837cfd35ec.png)
As you can see in this screenshot, event names that are long get cut off, especially if the calendar is not full screen.
For us this means the calendar has to be on it's own dashboard because no other gauges will fit alongside it.

I suspect this might not be a quick fix - I see that each day has a separate box to represent the event, so spanning the text across multiple days could be tricky, but would be a very useful feature to have.

**Comment by mikhail-vl** [comment]
@mpowelltech I will see what we can do.

**Comment by mikhail-vl** [comment]
@mpowelltech We released a new version 1.3.0 today. It's under Grafana team review.

  I will look to implement this feature in the upcoming release.

**Comment by mikhail-vl** [comment]
We added the Big Calendar library in v2.0.0, which allows to span labels across multiple days.
  Resolved in https://github.com/VolkovLabs/volkovlabs-calendar-panel/pull/106.
