### ISSUE TITLE
Regex not working

### ISSUE THREAD

**Issue by skyper5924** [VolkovLabs/volkovlabs-calendar-panel#95]
I ran into a problem that the regular expression that I use in override in Fields with name does not work, if I use a different visualization, for example, a regular table, then everything works without problems
![image](https://user-images.githubusercontent.com/60889551/228782463-2a3fc22d-b216-48d0-881d-60e6526d5581.png)

**Comment by mikhail-vl** [comment]
@skyper5924 Thank you for opening the issue. We removed unused Standard Options and added support for Units, Mappings, and Overrides.

  You can download the CI-signed artifact to test before the upcoming release: https://github.com/VolkovLabs/volkovlabs-calendar-panel/actions/runs/4570911744
