### ISSUE TITLE
Feature... Integrate with iCal?

### ISSUE THREAD

**Issue by daven1985** [VolkovLabs/volkovlabs-calendar-panel#99]
Afternoon,

Is it possible to sync this plugin with an iCAL URL?

Sorry if mentioned elsewhere. 

Thanks! So excited is possible as it may have changed how we do some displays at work!

**Comment by mikhail-vl** [comment]
@daven1985 It should be possible if you can retrieve iCal data using one of the existing Data Source. I am not sure if the iCal Data Source exists, maybe you can use JSON API or Infinity Data Source to retrieve data.

  I would love to know if you make it work.

**Comment by wokawoka** [comment]
I would also be interested to know if someone was able to import events from an ical feed.
For now I have just found a google calendar data source [here](https://grafana.com/grafana/plugins/mtanda-google-calendar-datasource/)

**Comment by mikhail-vl** [comment]
@wokawoka Google Calendar Data Source is an outdated Angular plugin not supported in Grafana 10.
 
  I don't see a lot of interest from the community in supporting iCloud or Google Calendar.
  Please consider storing events in any other data source supported by Grafana.

**Comment by wokawoka** [comment]
> @wokawoka Google Calendar Data Source is an outdated Angular plugin not supported in Grafana 10.
> 
> I don't see a lot of interest from the community in supporting iCloud or Google Calendar. Please consider storing events in any other data source supported by Grafana.

@mikhail-vl 
thank you for your answer.
Then I will investigate more and look for alternative solutions

**Comment by mikhail-vl** [comment]
@wokawoka Great! 

  Let us know if there is anything else.
